### ISSUE TITLE
结果很多“找人失败”

### ISSUE THREAD

**Issue by patrick-andstar** [Lynnette177/SINA-spider#1]
我的一个输出：
门徒电影
06月15日 18:59 1212 139
搜索页面 https://s.weibo.com/user?q=门徒电影&Refer=weibo_user
找人主页： https://weibo.cn/u/5143998400
找人失败
找人失败
找人失败
找人失败
找人失败

我目前修改的地方一个是cookie，一个是topic，其它没改

**Comment by Lynnette177** [comment]
cookie得改两个
&nbsp;


Mercy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月16日(星期天) 凌晨0:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Lynnette177/SINA-spider] 结果很多“找人失败” (Issue #1)














 
我的一个输出：
 门徒电影
 06月15日 18:59 1212 139
 搜索页面 https://s.weibo.com/user?q=门徒电影&amp;Refer=weibo_user
 找人主页： https://weibo.cn/u/5143998400
 找人失败
 找人失败
 找人失败
 找人失败
 找人失败
 
我目前修改的地方一个是cookie，一个是topic，其它没改

**Comment by patrick-andstar** [comment]
对，我headers_com和headers_cn都改了，大佬求助

**Comment by patrick-andstar** [comment]
一个cookie在：https://weibo.com。一个在：https://weibo.com/comment找的

**Comment by patrick-andstar** [comment]
ok了哥，我发现那个评论在weibo.cn/comment上就可以。难绷
